# Generated by Django 3.1 on 2020-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerId', models.CharField(max_length=100)),
                ('Survived', models.CharField(max_length=100)),
                ('Pclass', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('SibSp', models.CharField(max_length=100)),
                ('Parch', models.CharField(max_length=100)),
                ('Ticket', models.CharField(max_length=100)),
                ('Fare', models.CharField(max_length=100)),
                ('Cabin', models.CharField(max_length=100)),
                ('Embarked', models.CharField(max_length=100)),
            ],
        ),
    ]
